/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_top_ndk_Java2CJNI */

#ifndef _Included_com_top_ndk_Java2CJNI
#define _Included_com_top_ndk_Java2CJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_top_ndk_Java2CJNI
 * Method:    helloJNI
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_top_ndk_Java2CJNI_helloJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}



#endif
#endif
